nginx:
    nginx:
        survive:
            hosts: 'rec03,rec04'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_nginx_survive_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1
        log:
            hosts: 'rec03,rec04'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_nginx_log_abnormal'
                alarm_threhold:
                    - 'above'
                    - 0.005
        response_time:
            hosts: 'rec03,rec04'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_nginx_log_time_abnormal'
                time_threhold: 1
                alarm_threhold:
                    - 'above'
                    - 0.005

redis:
    biz:
        survive:
            hosts: 'rec01,rec02'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_redis_biz_survive_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1
        mem:
            hosts: 'rec01,rec02'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_redis_biz_mem_abnormal'
                alarm_threhold:
                    - 'above'
                     - 0.9

    cache:
        survive:
            hosts: 'rec05,rec06,rec07,rec08,rec09,rec10,rec11'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_redis_cache_survive_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1
        mem:
            hosts: 'rec05,rec06,rec07,rec08,rec09,rec10,rec11'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_redis_cache_mem_abnormal'
                alarm_threhold:
                    - 'above'
                    - 0.9

web_service:
    web_service:
        survive:
            hosts: 'rec01,rec02,rec03,rec04,rec05,rec06,rec07,rec08,rec09,rec10,rec11,rec12,rec13,rec14'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_web_service_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1

model_service:
    gbdt:
        survive:
            hosts: 'rec01,rec02,rec03,rec04,rec05,rec06,rec07,rec08,rec09,rec10,rec11,rec12,rec13,rec14'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_gbdt_model_service_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1

    hmf_v2:
        survive:
            hosts: 'rec01,rec02,rec03,rec04,rec05,rec06,rec07,rec08,rec09,rec10,rec11,rec12,rec13,rec14'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_hmf_v2_model_service_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1

    doc2vec:
        survive:
            hosts: 'rec01,rec02,rec03,rec04,rec05,rec06,rec07,rec08,rec09,rec10,rec11,rec12,rec13,rec14'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_doc2vec_model_service_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1

azkaban:
    executor:
        survive:
            hosts: 'data01'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_azkaban_executor_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1
    web:
        survive:
            alarm_title: 'SR_azkaban_web_abnormal'
            hosts: 'data01'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_azkaban_web_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1

supervisor:
    supervisor:
        survive:
            hosts: 'rec01,rec02,rec03,rec04,rec05,rec06,rec07,rec08,rec09,rec10,rec11,rec12,rec13,rec14'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_supervisor_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1

flink_job:
    InvalidItems:
        survive:
            hosts: 'data02'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_flink_job_survive_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1

semoniter:
    semoniter:
        url:
            hosts: 'data02'
            alarm_config:
                alarm_level: 'fatal'
                alarm_title: 'SR_semoniter_abnormal'
                alarm_threhold:
                    - 'neq'
                    - 1
